# xxl-job 

version: '3'
services:
  mysql:
    container_name: xxl-job-mysql       # 指定容器的名称
    image: mysql:8.0                   # 指定镜像和版本
    ports:
      - "${MYSQL_PORT}:3306" # 暴露端口
    environment: # 设置环境变量
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"           # 挂载数据目录，需要在模板文件下创建data文件夹
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d"      # 挂载配置文件目录 ， 需要在模板文件创建config文件夹
      - "${MYSQL_DIR}/init:/docker-entrypoint-initdb.d" # 挂载初始化sql语句
  xxl-job:
    container_name: xxl-job-admin
    image: xuxueli/xxl-job-admin:2.2.0
    ports:
      - "${XXL_PORT}:8080"
    links:
      - xxl-job-mysql
    volumes:
      - "${XXL_DIR}/data:/data" # 挂载数据目录
    environment:
      spring.datasource.url: jdbc:mysql://xxl-job-mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      spring.datasource.password: ${MYSQL_ROOT_PASSWORD}
