# 单机开发时使用

version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.8.8
    container_name: elasticsearch
    environment: 
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
