version: '2'
services:
    mysql:
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        image: "mysql:8.0"
        restart: always
        volumes:
            - "./_db:/var/lib/mysql"
            - "./conf/my.cnf:/etc/my.cnf"
            - "./init:/docker-entrypoint-initdb.d/"
        ports:
            - "3306:3306"
