version: '2'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
#  admin:
#    image: apache/dubbo-admin
#    depends_on:
#      - zookeeper
#    environment:
#      - admin.registry.address=zookeeper://192.168.3.30:2181
#      - admin.config-center=zookeeper://192.168.3.30:2181
#      - admin.metadata-report.address=zookeeper://192.168.3.30:2181
#    ports:
#      - "8080:8080"
